on: [push]
name: Tests
jobs:
  setup-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build containers
        run: docker-compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)

      - name: Composer install
        run: docker-compose run --rm -T php composer install --no-interaction --no-progress

      - name: Run Code Standards
        run: docker-compose run --rm -T php vendor/bin/phpcs

      - name: Run Unit Tests
        run: docker-compose run --rm -T php vendor/bin/phpunit tests/Unit

      - name: Run Feature Tests
        run: docker-compose run --rm -T php vendor/bin/phpunit tests/Feature
